language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - postgresql
before_install:
  - pip install -U pip
install:
  - pip install -r requirements/travis.txt
  - setup.py install
before_script:
  - psql -c 'create database mountaineer;' -U postgres
script:
  - export DJANGO_SETTINGS_MODULE="mountaineer.core.settings.travis"
  - export MNTNR_POSTGRES_HOST="localhost"
  - export MNTNR_POSTGRES_PORT="5432"
  - export MNTNR_POSTGRES_USER="postgres"
  - export MNTNR_POSTGRES_PASSWORD=""
  - export MNTNR_SECRET_KEY="asdfaireavjkjlnlkjhlj,mcxnvwoieurnalkjsdfh"
  - mountaineer/manage.py test
  #- coverage run mountaineer/manage.py test
after_script:
  - codeclimate-test-reporter --file .coverage